import { User42 } from './types';

export const MOCK_USERS: Record<string, User42> = {
  norminet: {
    id: 10001,
    email: 'norminet@42.fr',
    login: 'norminet',
    first_name: 'Norminette',
    last_name: 'The Cat',
    usual_full_name: 'Norminet',
    displayname: 'Norminet (Official 42 Mascot)',
    phone: '+33 1 42 42 42 42',
    image: {
      link: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=400&q=80',
      versions: {
        medium: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=400&q=80',
        large: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
      },
    },
    'staff?': true,
    correction_point: 42,
    pool_month: 'september',
    pool_year: '2013',
    location: 'Cluster 1 - Desk 42',
    wallet: 4242,
    campus: [
      {
        id: 1,
        name: 'Paris',
        time_zone: 'Europe/Paris',
        language: { name: 'Français', identifier: 'fr' },
        country: 'France',
        city: 'Paris',
      },
    ],
    cursus_users: [
      {
        id: 101,
        grade: 'Staff Legend',
        level: 21.0,
        cursus_id: 21,
        cursus: { id: 21, name: '42cursus', slug: '42cursus' },
        skills: [
          { id: 1, name: 'C Norm & Compliance', level: 21.0 },
          { id: 2, name: 'Unix & System', level: 19.85 },
          { id: 3, name: 'Algorithms & AI', level: 18.9 },
          { id: 4, name: 'Code Quality', level: 21.0 },
          { id: 5, name: 'Graphics & Math', level: 17.4 },
          { id: 6, name: 'Network & Security', level: 19.1 },
        ],
      },
      {
        id: 102,
        grade: 'Piscine Master',
        level: 9.99,
        cursus_id: 9,
        cursus: { id: 9, name: 'C Piscine', slug: 'c-piscine' },
        skills: [
          { id: 1, name: 'Imperative programming', level: 9.99 },
          { id: 2, name: 'Rigor', level: 9.99 },
        ],
      },
    ],
    projects_users: [
      {
        id: 201,
        occurrence: 0,
        final_mark: 125,
        status: 'finished',
        'validated?': true,
        project: { id: 1314, name: 'Libft', slug: '42cursus-libft' },
        cursus_ids: [21],
        marked_at: '2023-01-15T12:00:00.000Z',
      },
      {
        id: 202,
        occurrence: 0,
        final_mark: 115,
        status: 'finished',
        'validated?': true,
        project: { id: 1315, name: 'get_next_line', slug: '42cursus-get_next_line' },
        cursus_ids: [21],
        marked_at: '2023-02-10T15:30:00.000Z',
      },
      {
        id: 203,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1316, name: 'ft_printf', slug: '42cursus-ft_printf' },
        cursus_ids: [21],
        marked_at: '2023-03-01T10:15:00.000Z',
      },
      {
        id: 204,
        occurrence: 0,
        final_mark: 125,
        status: 'finished',
        'validated?': true,
        project: { id: 1320, name: 'minishell', slug: '42cursus-minishell' },
        cursus_ids: [21],
        marked_at: '2023-05-20T18:00:00.000Z',
      },
      {
        id: 205,
        occurrence: 0,
        final_mark: 125,
        status: 'finished',
        'validated?': true,
        project: { id: 1330, name: 'ft_transcendence', slug: '42cursus-ft_transcendence' },
        cursus_ids: [21],
        marked_at: '2023-11-28T16:45:00.000Z',
      },
    ],
    achievements: [
      { id: 1, name: 'Norme Sentinel', description: 'Zero Norme errors found across 100 projects', tier: 'gold' },
      { id: 2, name: 'Pedagogy Guardian', description: 'Assisted hundreds of students during evaluations', tier: 'platinum' },
      { id: 3, name: 'Master of Clean Code', description: 'Code readability and efficiency at 100%', tier: 'gold' },
    ],
    isDemo: true,
  },
  ykuru: {
    id: 10042,
    email: 'ykuru@student.42istanbul.com.tr',
    login: 'ykuru',
    first_name: 'Yusuf',
    last_name: 'Kuru',
    usual_full_name: 'Yusuf Kuru',
    displayname: 'Yusuf Kuru',
    phone: '+90 532 420 4242',
    image: {
      link: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      versions: {
        medium: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        large: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
      },
    },
    'staff?': false,
    correction_point: 7,
    pool_month: 'july',
    pool_year: '2022',
    location: 'c2r4s8',
    wallet: 385,
    campus: [
      {
        id: 48,
        name: 'Istanbul',
        time_zone: 'Europe/Istanbul',
        language: { name: 'Türkçe', identifier: 'tr' },
        country: 'Turkey',
        city: 'Istanbul',
      },
    ],
    cursus_users: [
      {
        id: 301,
        grade: 'Cadet',
        level: 10.42,
        cursus_id: 21,
        cursus: { id: 21, name: '42cursus', slug: '42cursus' },
        skills: [
          { id: 1, name: 'Algorithms & AI', level: 12.15 },
          { id: 2, name: 'Unix & System Programming', level: 11.8 },
          { id: 3, name: 'Imperative programming', level: 13.4 },
          { id: 4, name: 'Graphics & Math', level: 8.9 },
          { id: 5, name: 'Network & System Administration', level: 9.75 },
          { id: 6, name: 'Object-Oriented Programming', level: 10.6 },
          { id: 7, name: 'Web & Databases', level: 9.2 },
          { id: 8, name: 'Security', level: 7.5 },
        ],
      },
      {
        id: 302,
        grade: 'Pisciner',
        level: 6.85,
        cursus_id: 9,
        cursus: { id: 9, name: 'C Piscine', slug: 'c-piscine' },
        skills: [
          { id: 1, name: 'Imperative programming', level: 7.2 },
          { id: 2, name: 'Rigor', level: 8.5 },
          { id: 3, name: 'Algorithms', level: 6.9 },
        ],
      },
    ],
    projects_users: [
      {
        id: 401,
        occurrence: 0,
        final_mark: 125,
        status: 'finished',
        'validated?': true,
        project: { id: 1314, name: 'Libft', slug: '42cursus-libft' },
        cursus_ids: [21],
        marked_at: '2022-09-12T14:30:00.000Z',
      },
      {
        id: 402,
        occurrence: 0,
        final_mark: 115,
        status: 'finished',
        'validated?': true,
        project: { id: 1315, name: 'get_next_line', slug: '42cursus-get_next_line' },
        cursus_ids: [21],
        marked_at: '2022-10-05T11:20:00.000Z',
      },
      {
        id: 403,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1316, name: 'ft_printf', slug: '42cursus-ft_printf' },
        cursus_ids: [21],
        marked_at: '2022-10-24T16:00:00.000Z',
      },
      {
        id: 404,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1317, name: 'Born2beRoot', slug: 'born2beroot' },
        cursus_ids: [21],
        marked_at: '2022-11-18T10:45:00.000Z',
      },
      {
        id: 405,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1321, name: 'push_swap', slug: '42cursus-push_swap' },
        cursus_ids: [21],
        marked_at: '2022-12-15T13:10:00.000Z',
      },
      {
        id: 406,
        occurrence: 0,
        final_mark: 105,
        status: 'finished',
        'validated?': true,
        project: { id: 1322, name: 'pipex', slug: 'pipex' },
        cursus_ids: [21],
        marked_at: '2023-01-20T17:00:00.000Z',
      },
      {
        id: 407,
        occurrence: 1,
        final_mark: 42,
        status: 'finished',
        'validated?': false,
        project: { id: 1323, name: 'so_long', slug: 'so_long' },
        cursus_ids: [21],
        marked_at: '2023-02-14T09:30:00.000Z',
      },
      {
        id: 408,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1324, name: 'Philosophers', slug: '42cursus-philosophers' },
        cursus_ids: [21],
        marked_at: '2023-04-02T15:20:00.000Z',
      },
      {
        id: 409,
        occurrence: 0,
        final_mark: 110,
        status: 'finished',
        'validated?': true,
        project: { id: 1320, name: 'minishell', slug: '42cursus-minishell' },
        cursus_ids: [21],
        marked_at: '2023-06-30T18:40:00.000Z',
      },
      {
        id: 410,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1328, name: 'NetPractice', slug: 'netpractice' },
        cursus_ids: [21],
        marked_at: '2023-08-10T14:15:00.000Z',
      },
      {
        id: 411,
        occurrence: 0,
        final_mark: 115,
        status: 'finished',
        'validated?': true,
        project: { id: 1329, name: 'cub3d', slug: 'cub3d' },
        cursus_ids: [21],
        marked_at: '2023-11-05T19:00:00.000Z',
      },
      {
        id: 412,
        occurrence: 0,
        final_mark: null,
        status: 'in_progress',
        'validated?': null,
        project: { id: 1331, name: 'webserv', slug: 'webserv' },
        cursus_ids: [21],
      },
      {
        id: 413,
        occurrence: 0,
        final_mark: null,
        status: 'in_progress',
        'validated?': null,
        project: { id: 1330, name: 'ft_transcendence', slug: '42cursus-ft_transcendence' },
        cursus_ids: [21],
      },
    ],
    achievements: [
      { id: 1, name: 'Welcome, Cadet', description: 'Passed the C Piscine and entered 42cursus', tier: 'bronze' },
      { id: 2, name: 'Shell Whisperer', description: 'Created a working shell parsing pipes and redirects', tier: 'silver' },
      { id: 3, name: 'Raycasting Pioneer', description: 'Rendered a 3D raycaster labyrinth inspired by Wolfenstein 3D', tier: 'silver' },
      { id: 4, name: 'Multithreading Sage', description: 'Mastered mutexes and avoided dining philosopher starvation', tier: 'silver' },
      { id: 5, name: 'Peer Review Champion', description: 'Completed over 50 peer evaluations', tier: 'gold' },
    ],
    isDemo: true,
  },
  marvin: {
    id: 10002,
    email: 'marvin@42.fr',
    login: 'marvin',
    first_name: 'Marvin',
    last_name: 'Paranoid',
    usual_full_name: 'Marvin the Bot',
    displayname: 'Marvin (Evaluation Bot)',
    phone: null,
    image: {
      link: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=400&q=80',
      versions: {
        medium: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=400&q=80',
        large: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
      },
    },
    'staff?': false,
    correction_point: 999,
    pool_month: 'january',
    pool_year: '2020',
    location: null,
    wallet: 9999,
    campus: [
      {
        id: 1,
        name: 'Paris',
        time_zone: 'Europe/Paris',
        country: 'France',
        city: 'Paris',
      },
    ],
    cursus_users: [
      {
        id: 501,
        grade: 'Member',
        level: 16.42,
        cursus_id: 21,
        cursus: { id: 21, name: '42cursus', slug: '42cursus' },
        skills: [
          { id: 1, name: 'Algorithms & AI', level: 17.5 },
          { id: 2, name: 'Unix', level: 16.2 },
          { id: 3, name: 'Imperative programming', level: 18.0 },
          { id: 4, name: 'Graphics', level: 14.3 },
          { id: 5, name: 'Network & System Administration', level: 16.8 },
        ],
      },
    ],
    projects_users: [
      {
        id: 601,
        occurrence: 0,
        final_mark: 125,
        status: 'finished',
        'validated?': true,
        project: { id: 1314, name: 'Libft', slug: '42cursus-libft' },
        cursus_ids: [21],
        marked_at: '2021-03-10T11:00:00.000Z',
      },
      {
        id: 602,
        occurrence: 2,
        final_mark: 0,
        status: 'finished',
        'validated?': false,
        project: { id: 1320, name: 'minishell', slug: '42cursus-minishell' },
        cursus_ids: [21],
        marked_at: '2021-06-25T14:30:00.000Z',
      },
    ],
    achievements: [
      { id: 1, name: 'Brain the Size of a Planet', description: 'Infinite computational capacity', tier: 'gold' },
    ],
    isDemo: true,
  },
};

export function generateDynamicMockUser(login: string): User42 {
  const cleanLogin = login.toLowerCase().trim();
  if (MOCK_USERS[cleanLogin]) {
    return MOCK_USERS[cleanLogin];
  }

  // Generate deterministic but realistic student profile for any username
  let hash = 0;
  for (let i = 0; i < cleanLogin.length; i++) {
    hash = (hash << 5) - hash + cleanLogin.charCodeAt(i);
    hash |= 0;
  }
  const absHash = Math.abs(hash);
  const levelNum = ((absHash % 1400) / 100) + 1.5; // level 1.50 to 15.50
  const roundedLevel = Math.round(levelNum * 100) / 100;
  const wallet = (absHash % 450) + 20;
  const correctionPoints = (absHash % 9) + 1;
  const isOnline = (absHash % 3) === 0;
  const row = (absHash % 8) + 1;
  const col = (absHash % 12) + 1;
  const seat = (absHash % 24) + 1;
  const location = isOnline ? `c${row}r${col}p${seat}` : null;

  const sampleAvatars = [
    'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
  ];
  const avatar = sampleAvatars[absHash % sampleAvatars.length];

  const capitalizedLogin = cleanLogin.charAt(0).toUpperCase() + cleanLogin.slice(1);

  return {
    id: 20000 + (absHash % 50000),
    email: `${cleanLogin}@student.42.fr`,
    login: cleanLogin,
    first_name: capitalizedLogin,
    last_name: '42Student',
    usual_full_name: `${capitalizedLogin} 42`,
    displayname: `${capitalizedLogin} (Demo Profile)`,
    phone: `+33 6 ${String(absHash % 90000000 + 10000000).replace(/(\d{2})/g, '$1 ').trim()}`,
    image: {
      link: avatar,
      versions: {
        medium: avatar,
        large: avatar,
      },
    },
    'staff?': false,
    correction_point: correctionPoints,
    pool_month: 'august',
    pool_year: '2023',
    location: location,
    wallet: wallet,
    campus: [
      {
        id: 1,
        name: 'Paris',
        time_zone: 'Europe/Paris',
        country: 'France',
        city: 'Paris',
      },
    ],
    cursus_users: [
      {
        id: 701,
        grade: roundedLevel >= 9 ? 'Cadet' : 'Novice',
        level: roundedLevel,
        cursus_id: 21,
        cursus: { id: 21, name: '42cursus', slug: '42cursus' },
        skills: [
          { id: 1, name: 'Algorithms & AI', level: Math.round(Math.min(21, roundedLevel * 1.1) * 100) / 100 },
          { id: 2, name: 'Unix & System', level: Math.round(Math.min(21, roundedLevel * 0.95) * 100) / 100 },
          { id: 3, name: 'Imperative programming', level: Math.round(Math.min(21, roundedLevel * 1.15) * 100) / 100 },
          { id: 4, name: 'Graphics & Math', level: Math.round(Math.min(21, roundedLevel * 0.8) * 100) / 100 },
          { id: 5, name: 'Network & System Administration', level: Math.round(Math.min(21, roundedLevel * 0.85) * 100) / 100 },
          { id: 6, name: 'Company experience', level: Math.round(Math.min(21, roundedLevel * 0.5) * 100) / 100 },
        ],
      },
      {
        id: 702,
        grade: 'Pisciner',
        level: 7.42,
        cursus_id: 9,
        cursus: { id: 9, name: 'C Piscine', slug: 'c-piscine' },
        skills: [
          { id: 1, name: 'Imperative programming', level: 7.8 },
          { id: 2, name: 'Rigor', level: 8.1 },
        ],
      },
    ],
    projects_users: [
      {
        id: 801,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1314, name: 'Libft', slug: '42cursus-libft' },
        cursus_ids: [21],
        marked_at: '2023-10-10T14:00:00.000Z',
      },
      {
        id: 802,
        occurrence: 0,
        final_mark: 115,
        status: 'finished',
        'validated?': true,
        project: { id: 1315, name: 'get_next_line', slug: '42cursus-get_next_line' },
        cursus_ids: [21],
        marked_at: '2023-11-02T16:20:00.000Z',
      },
      {
        id: 803,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1316, name: 'ft_printf', slug: '42cursus-ft_printf' },
        cursus_ids: [21],
        marked_at: '2023-11-20T11:00:00.000Z',
      },
      {
        id: 804,
        occurrence: 1,
        final_mark: 35,
        status: 'finished',
        'validated?': false,
        project: { id: 1321, name: 'push_swap', slug: '42cursus-push_swap' },
        cursus_ids: [21],
        marked_at: '2024-01-15T10:00:00.000Z',
      },
      {
        id: 805,
        occurrence: 0,
        final_mark: 100,
        status: 'finished',
        'validated?': true,
        project: { id: 1317, name: 'Born2beRoot', slug: 'born2beroot' },
        cursus_ids: [21],
        marked_at: '2024-02-12T15:45:00.000Z',
      },
      {
        id: 806,
        occurrence: 0,
        final_mark: null,
        status: 'in_progress',
        'validated?': null,
        project: { id: 1320, name: 'minishell', slug: '42cursus-minishell' },
        cursus_ids: [21],
      },
    ],
    achievements: [
      { id: 1, name: 'Cadet Infiltration', description: 'Admitted to 42 Common Core', tier: 'bronze' },
      { id: 2, name: 'Library Builder', description: 'Completed Libft with all standard C functions', tier: 'silver' },
    ],
    isDemo: true,
  };
}
